apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.spring.apiServiceName }}
spec:
  replicas: {{ .Values.spring.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.spring.apiServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.spring.apiServiceName }}
    spec:
      containers:
        - name: {{ .Values.spring.apiServiceName }}
          image: {{ .Values.spring.repository }}
          ports:
            - containerPort: {{ .Values.spring.port }}
          env:
            - name: AT_DB_HOST
              value: "{{ .Values.spring.env.DATABASE_URL }}{{ .Values.postgres.dbServiceName }}"
            - name: AT_DB_PORT
              value: "{{ .Values.postgres.port }}"
            - name: AT_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: AT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: AT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: SPRING_LOGGING_LEVEL_ROOT
              value: {{ .Values.spring.env.SPRING_LOGGING_LEVEL_ROOT }}
            - name: SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
              value: {{ .Values.spring.env.SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK }}
          livenessProbe:
            httpGet:
              path: {{ .Values.spring.healthCheckEndpoint }}
              port: {{ .Values.spring.port }}
            initialDelaySeconds: {{ .Values.spring.healthCheckDelay }}
            periodSeconds: {{ .Values.spring.healthCheckPeriod }}
          readinessProbe:
            httpGet:
              path: {{ .Values.spring.healthCheckEndpoint }}
              port: {{ .Values.spring.port }}
            initialDelaySeconds: {{ .Values.spring.healthCheckDelay }}
            periodSeconds: {{ .Values.spring.healthCheckPeriod }}
