apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.dbServiceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.dbServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.dbServiceName }}
    spec:
      containers:
        - name: {{ .Values.postgres.dbServiceName }}
          image: {{ .Values.postgres.repository }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: {{ .Chart.Name }}-postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: {{ .Chart.Name }}-postgres-volume
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
