apiVersion: v2
name: at-app-kubernetes
description: A Helm chart for Kubernetes

type: application

version: 0.0.3

appVersion: "0.0.3"

dependencies:
  - name: ingress-nginx
    version: "4.12.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
