apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spring.apiServiceName }}
spec:
  ports:
    - port: {{ .Values.spring.servicePort }}
      targetPort: {{ .Values.spring.port }}
  selector:
    app: {{ .Values.spring.apiDeploymentName }}
  type: {{ .Values.spring.serviceType }}
