apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secrets.name }}
type: {{ .Values.postgres.secrets.type }}
data:
  POSTGRES_USER: {{ .Values.postgres.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.database | b64enc }}
