apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.persistence.pvClaimName }}
  labels:
    type: {{ .Values.postgres.persistence.type }}
spec:
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.postgres.persistence.size }}
  accessModes:
    - {{ .Values.postgres.persistence.accessModes }}
  hostPath:
    path: {{ .Values.postgres.persistence.path }}
